services:
  postgres:
    container_name: ${APP_SHORT_NAME}-postgres
    image: postgres:15.1
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: ${DATABASE_TZ}
      PGTZ: ${DATABASE_PGTZ}
  adminer:
    container_name: ${APP_SHORT_NAME}-adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
